/** Tài khoản, gói, thanh toán, quản trị (BE6) — một phần của danh bạ `routes`. */

import {
  AccountDeleteResult,
  AdminActivatePlanInput,
  AdminActivatePlanResult,
  AdminDoneResult,
  AdminResetPasswordInput,
  BankWebhookBody,
  BankWebhookResult,
  MeProfile,
  MeProfilePatch,
  PaymentIntentCreateInput,
  PaymentIntentsList,
  PaymentIntentView,
  ReferralClaimInput,
  ReferralClaimResult,
  SubscriptionView,
} from './account.js';
import type { RouteDef } from './route-def.js';

export const accountRoutes = {
  meProfile: {
    method: 'GET',
    path: '/v1/me/profile',
    summary: 'Hồ sơ của người đang đăng nhập: tên, tên đăng nhập, email khôi phục, mã giới thiệu',
    auth: 'user',
    response: MeProfile,
  },
  meProfileUpdate: {
    method: 'PATCH',
    path: '/v1/me/profile',
    summary: 'Sửa tên, tên đăng nhập, email khôi phục. Số điện thoại là khoá đăng nhập — không đổi ở đây',
    auth: 'user',
    body: MeProfilePatch,
    response: MeProfile,
  },
  meDelete: {
    method: 'DELETE',
    path: '/v1/me',
    summary:
      'Xoá tài khoản THẬT: ảnh → dữ liệu của tổ chức mình là chủ duy nhất → tài khoản đăng nhập. Còn người khác trong tổ chức → 422',
    auth: 'user',
    response: AccountDeleteResult,
    rateLimitPerMinute: 5,
  },
  meSubscription: {
    method: 'GET',
    path: '/v1/me/subscription',
    summary: 'Gói của tổ chức đang làm việc, kèm bảng giá và có tự mua được không',
    auth: 'org',
    permission: 'billing:manage',
    response: SubscriptionView,
  },
  billingIntentsList: {
    method: 'GET',
    path: '/v1/billing/intents',
    summary: 'Các lần định chuyển khoản gần đây, mới nhất trước',
    auth: 'org',
    permission: 'billing:manage',
    response: PaymentIntentsList,
  },
  billingIntentsCreate: {
    method: 'POST',
    path: '/v1/billing/intents',
    summary: 'Chủ vựa định chuyển khoản mua gói — trả mã đối soát và nội dung chuyển khoản. Doanh nghiệp, nông dân → 403',
    auth: 'org',
    permission: 'billing:manage',
    body: PaymentIntentCreateInput,
    response: PaymentIntentView,
  },
  referralsClaim: {
    method: 'POST',
    path: '/v1/referrals/claim',
    summary: 'Ghi nhận người mời mình — đúng một lần. Luôn 200; không nói vì sao mã không dùng được',
    auth: 'user',
    body: ReferralClaimInput,
    response: ReferralClaimResult,
    rateLimitPerMinute: 10,
  },
  webhooksBank: {
    method: 'POST',
    path: '/v1/webhooks/bank',
    summary:
      'Casso / SePay báo tiền vào. Bí mật ở header `secure-token` hoặc `Authorization: Apikey …`. Chống trùng theo mã giao dịch ngân hàng',
    auth: 'public',
    body: BankWebhookBody,
    response: BankWebhookResult,
    errors: ['UNAUTHENTICATED'],
  },
  adminActivatePlan: {
    method: 'POST',
    path: '/v1/admin/plans/activate',
    summary: 'Quản trị viên mở / gia hạn gói bằng tay (chuyển khoản sai nội dung, gói doanh nghiệp). Gọi lại an toàn',
    auth: 'admin',
    body: AdminActivatePlanInput,
    response: AdminActivatePlanResult,
    errors: ['NOT_FOUND'],
  },
  adminResetPassword: {
    method: 'POST',
    path: '/v1/admin/users/reset-password',
    summary: 'Quản trị viên đặt lại mật khẩu cho người không khai email khôi phục — đã xác minh danh tính ngoài app',
    auth: 'admin',
    body: AdminResetPasswordInput,
    response: AdminDoneResult,
    errors: ['NOT_FOUND'],
  },
} as const satisfies Record<string, RouteDef>;
