/** Đơn hàng, đặt lịch, thông báo (BE5) — một phần của danh bạ `routes`. */

import {
  NotificationsQuery,
  NotificationsReadInput,
  NotificationsReadResult,
  NotificationsResult,
} from './notifications.js';
import {
  OrderCreateInput,
  OrderDetail,
  OrderIdParams,
  OrderScheduleInput,
  OrdersListQuery,
  OrdersListResult,
  OrderSummary,
  OrderTransitionInput,
} from './orders.js';
import type { RouteDef } from './route-def.js';

export const orderRoutes = {
  ordersList: {
    method: 'GET',
    path: '/v1/orders',
    summary: 'Đơn của tổ chức đang làm việc, cả hai phía (mình bán / mình mua), mới tạo trước. Cần order:create hoặc order:respond',
    auth: 'org',
    query: OrdersListQuery,
    response: OrdersListResult,
  },
  ordersCreate: {
    method: 'POST',
    path: '/v1/orders',
    summary: 'Tạo đơn bán hoặc mua với một tổ chức đã kết nối đúng chiều',
    auth: 'org',
    permission: 'order:create',
    body: OrderCreateInput,
    response: OrderSummary,
    errors: ['LINK_REQUIRED'],
  },
  orderGet: {
    method: 'GET',
    path: '/v1/orders/:id',
    summary: 'Một đơn kèm lịch sử chuyển trạng thái',
    auth: 'org',
    params: OrderIdParams,
    response: OrderDetail,
    errors: ['NOT_FOUND'],
  },
  orderAccept: {
    method: 'POST',
    path: '/v1/orders/:id/accept',
    summary: 'Bên nhận đơn nhận đơn (submitted → accepted)',
    auth: 'org',
    permission: 'order:respond',
    params: OrderIdParams,
    body: OrderTransitionInput,
    response: OrderSummary,
    errors: ['ORDER_STATE_CHANGED', 'NOT_FOUND'],
  },
  orderReject: {
    method: 'POST',
    path: '/v1/orders/:id/reject',
    summary: 'Bên nhận đơn từ chối (submitted → cancelled)',
    auth: 'org',
    permission: 'order:respond',
    params: OrderIdParams,
    body: OrderTransitionInput,
    response: OrderSummary,
    errors: ['ORDER_STATE_CHANGED', 'NOT_FOUND'],
  },
  orderSchedule: {
    method: 'POST',
    path: '/v1/orders/:id/schedule',
    summary: 'Bên mua hẹn lịch lấy hàng (accepted|scheduled → scheduled)',
    auth: 'org',
    permission: 'order:respond',
    params: OrderIdParams,
    body: OrderScheduleInput,
    response: OrderSummary,
    errors: ['ORDER_STATE_CHANGED', 'NOT_FOUND'],
  },
  orderCancel: {
    method: 'POST',
    path: '/v1/orders/:id/cancel',
    summary: 'Một trong hai bên huỷ đơn chưa hoàn thành. Bên tạo cần order:create, bên nhận cần order:respond',
    auth: 'org',
    params: OrderIdParams,
    body: OrderTransitionInput,
    response: OrderSummary,
    errors: ['ORDER_STATE_CHANGED', 'NOT_FOUND'],
  },
  notificationsList: {
    method: 'GET',
    path: '/v1/notifications',
    summary: 'Thông báo của tổ chức đang làm việc, mới nhất trước, kèm số chưa đọc. App hỏi khi mở và mỗi 60 giây',
    auth: 'org',
    query: NotificationsQuery,
    response: NotificationsResult,
  },
  notificationsRead: {
    method: 'POST',
    path: '/v1/notifications/read',
    summary: 'Đánh dấu đã đọc một số thông báo, hoặc tất cả khi bỏ trống ids',
    auth: 'org',
    body: NotificationsReadInput,
    response: NotificationsReadResult,
  },
} as const satisfies Record<string, RouteDef>;
