/** Nhân viên, chi nhánh, báo cáo tổng (BE7) — một phần của danh bạ `routes`. */

import {
  IdParams,
  OrgBranch,
  OrgBranchCreateInput,
  OrgBranchesList,
  OrgBranchPatch,
  OrgMember,
  OrgMemberCreateInput,
  OrgMemberPatch,
  OrgMembersList,
  ReportSummary,
  ReportSummaryQuery,
} from './org.js';
import type { RouteDef } from './route-def.js';

export const orgRoutes = {
  orgMembersList: {
    method: 'GET',
    path: '/v1/org/members',
    summary: 'Người trong tổ chức đang làm việc: vai trò, chi nhánh, trạng thái',
    auth: 'org',
    permission: 'staff:manage',
    response: OrgMembersList,
  },
  orgMembersCreate: {
    method: 'POST',
    path: '/v1/org/members',
    summary: 'Chủ tạo tài khoản cho người cân / quản lý (tên, số điện thoại, mật khẩu ban đầu) và gắn vào tổ chức',
    auth: 'org',
    permission: 'staff:manage',
    body: OrgMemberCreateInput,
    response: OrgMember,
    errors: ['NOT_FOUND'],
    rateLimitPerMinute: 20,
  },
  orgMemberUpdate: {
    method: 'PATCH',
    path: '/v1/org/members/:id',
    summary: 'Đổi vai trò hoặc chi nhánh của một người (không phải chủ, không phải chính mình)',
    auth: 'org',
    permission: 'staff:manage',
    params: IdParams,
    body: OrgMemberPatch,
    response: OrgMember,
    errors: ['NOT_FOUND'],
  },
  orgMemberRemove: {
    method: 'DELETE',
    path: '/v1/org/members/:id',
    summary: 'Gỡ một người khỏi tổ chức — mất quyền ngay. Gọi lại an toàn',
    auth: 'org',
    permission: 'staff:manage',
    params: IdParams,
    response: OrgMember,
    errors: ['NOT_FOUND'],
  },
  orgBranchesList: {
    method: 'GET',
    path: '/v1/org/branches',
    summary: 'Chi nhánh của tổ chức, kèm giới hạn của gói và số đang dùng',
    auth: 'org',
    permission: 'branch:manage',
    response: OrgBranchesList,
  },
  orgBranchesCreate: {
    method: 'POST',
    path: '/v1/org/branches',
    summary: 'Tạo chi nhánh — vượt giới hạn của gói thì BRANCH_LIMIT',
    auth: 'org',
    permission: 'branch:manage',
    body: OrgBranchCreateInput,
    response: OrgBranch,
    errors: ['BRANCH_LIMIT'],
  },
  orgBranchUpdate: {
    method: 'PATCH',
    path: '/v1/org/branches/:id',
    summary: 'Đổi tên, địa chỉ; lưu trữ (chưa ai gắn) hoặc dùng lại (trong giới hạn của gói)',
    auth: 'org',
    permission: 'branch:manage',
    params: IdParams,
    body: OrgBranchPatch,
    response: OrgBranch,
    errors: ['BRANCH_LIMIT', 'NOT_FOUND'],
  },
  reportsSummary: {
    method: 'GET',
    path: '/v1/reports/summary',
    summary: 'Tổng mua / bán / đã trả / còn nợ trong khoảng thời gian, chia theo chi nhánh — tính phía server',
    auth: 'org',
    permission: 'report:view',
    query: ReportSummaryQuery,
    response: ReportSummary,
    errors: ['NOT_FOUND'],
  },
} as const satisfies Record<string, RouteDef>;
